
public class FaktenAbfrage {

    String[] fakten = new String[]	{
            "Drache heisst mit wirklichem Namen >Paul Daniel Gerhardt<.",
            "Pilot und Co Pilot duerfen im Cockpit nicht das gleiche Essen essen",
            "Eulen Babys schlafen auf dem Kopf",
            "Das Lied >Ich bin doch kein Robotor< ist vom Saenger Tim Bendzko",
            "In Daenemark gibt es den Beruf >Butterbrotjungfrau<",
            //5
            "In Deutschland gibt es den Beruf >Eierschalensollbruchstellenverursacher<",
            "Bayern gehoert zur >Staatenrepublik Deutschland<",
            "Das Lied >Wow.< ist vom Saenger GoonRock",
            "Das Lied >High Hopes< ist von der Gruppe LMFAO",
            "Beamte im mittleren Dienst bekommen um die 1600 Euro Pension wenn sie in Rente gehen",
            //10
            "Diese Person hielt Albert Einstein fuer die schlauste Person der Welt",
            "Wegen welchem Industriemagnat gab es erste Ideen ueber das Wochenende",
            "Das Lied >Haus am See< ist vom Saenger Peter Fox",
            "Das Lied >Wow.< ist vom Saenger Post Malone",
            "Unsere gemeinsame Playlist heisst >Galo<",
            //15
            "Unsere gemeinsame Playlist heisst >GALO<",
            "Die Hauptstadt von Armenien ist Jerewan",
            "Die Hauptstadt von Aserbaidschan ist Baku",
            "Die Hauptstadt von Aethiopien ist Addis Abeba",
            "Die Haupstadt von Argentinien ist Buenos Aires",
            //20
            "Die Hauptstadt von Algerien ist Algeria",
            "Die Hauptstadt von Australien ist Sydney",
            "Die Hauptstadt von den Bahamas ist Manama",
            "Die Hauptstadt von Bahrain ist Nassau",
            "Die Hauptstadt von Botswana ist Sarajevo",
            //25
            "Die Hauptstadt von Dominica ist Roseau",
            "Die Hauptstadt von Ecuador ist Quito",
            "Die Hauptstadt von Eritrea ist Asmara",
            "Die Hauptstadt von Fidschi ist Suva",
            "Die Hauptstadt von Gabun ist Libreville",
            //30
            "Die Hauptstadt von Georgien ist Tiflis",
            "Die Hauptstadt von Ghana ist Accra",
            "Die Hauptstadt von Guatemala ist Guatemala-Stadt",
            "Die Hauptstadt von Indonesien ist Jakarta",
            "Die Hauptstadt von Jamaika ist Kingston",
            //35
            "Die Hauptstadt von Jordanien ist Amman",
            "Die Hauptstadt von Kasachstan ist Astana",
            "Die Hauptstadt von Kirgisistan ist Bischkek",
            "Die Hauptstadt von Kiribati ist South Tarawa",
            "Die Hauptstadt von Komoren ist Moroni",
            //40
            "Die Hauptstadt von der Republik Kongo ist Brazzaville",
            "Die Hauptstadt von Kroatien ist Zagreb",
            "Die Hauptstadt von Kuwait ist Kuwait",
            "Die Hauptstadt von Laos ist Vientiane",
            "Die Hauptstadt von Lesotho ist Maseru",
            //45
            "Die Hauptstadt von Libanon ist Riga",
            "Die Hauptstadt von Laos ist Beirut",
            "Die Hauptstadt von Kuwait ist Kinshasa",
            "Die Hauptstadt von Malaysia ist Lilongwe",
            "Die Hauptstadt von Mali ist Male",
            //50
            "Die Hauptstadt von Malta ist Rabat",
            "Die Hauptstadt von Monaco ist Maputo",
            "Die Hauptstadt von Myanmar ist Maputo",
            "Die Hauptstadt von Namibia ist Port Louis",
            "Die Hauptstadt von Nauru ist Windhoek",
            //55
            "Die Hauptstadt von Osttimor ist Maskat",
            "Die Hauptstadt von Pakistan ist Dili",
            "Die Hauptstadt vom Oman ist Islamabad",
            "Die Hauptstadt von Palau ist Ngerulmud",
            "Die Hauptstadt von Ruanda ist Lusaka",
            //60
            "Die Anti Baby Pille fuer ein Flusspferd wiegt 120g",
            "ca. 50% aller Literatur ueber das Thema Steuern sind auf deutsch",
            "Wenn man in Alkohol badet, dann wird man betrunken",
            "Aus einer Boing 747 lassen sich ca. 6 Millionen Bierdosen machen",
            "Der haeufigste Einbuchstabige Familienname ist O",
            //65
            "Waehrend die Mauer zwischen West- und Ostdeutschland viel war Angela Merkel in der Sauna",
            "Es gibt kein deutsches Wort welches sich auf Mensch reimt",
            "Bakterien machen 1-4 Kilo deines Koerpergewichts aus",
            "Amumu hat mehr als 13 Skins",
            "Warwick hat mehr als 14 Skins",
            //70
            "Jhin hat mehr als 8 Skins",
            "Urgot hat mehr als 6 Skins",
            "Ivern hat mehr als 4 Skins",
            "Ahri hat mehr als 16 Skins",
            "Lux hat mehr als 18 Skins",
            //75
            "Morgana hat mehr als 17 Skins",
            "Teemo hat mehr als 22 Skins",
            "Aurelion Sol hat mehr als 15 Skins",
            "Sett hat mehr als 16 Skins",
            "Twisted Fate hat mehr als 23 Skins",
            //80
            "Kai sa hat mehr als 19 Skins",
            "Senna hat mehr als 15 Skins",
            "Varus hat mehr als 23 Skins",
            "Soraka hat weniger als 15 Skins",
            "Singed hat weniger als 11 Skins",
            //85
            "Das Musikvideo zu Just cant get enough wurde in Florida gedreht",
            "Das Musikvideo zu Just cant get enough wurde in Miami gedreht",
            "Das Musikvideo zu Just cant get enough wurde in Kalifornien gedreht",
            "Das Musikvideo zu Just cant get enough wurde in New York gedreht",
            "Das Musikvideo zu Just cant get enough wurde in Japan gedreht",
            //90
            "Juju und Henning May haben min. ein Lied zusammen gemacht",
            "Fergie und Ludacris haben min. ein Lied zusammen gemacht",
            "KIZ und Henning May haben min. ein Lied zusammen gemacht",
            "Robin Schulz und Alida haben min. ein Lied zusammen gemacht",
            "Post Malone und 21Savage haben min. ein Lied zusammen gemacht",
            //95
            "Linkin Park und Kanye West haben min. ein Lied zusammen gemacht",
            "Eminem und Dieter Bohlen haben min. ein Lied zusammen gemacht",
            "Die toten Hosen und Farid Bang haben min. ein Lied zusammen gemacht",
            "Adele und Eko fresh haben min. ein Lied zusammen gemacht",
            "Sido und 2 pac haben min. ein Lied zusammen gemacht",
            //100
            "Das Lied Im a Wanted Man ist vom Saenger",
            "Das Lied Koenig der Luegner ist vom Saenger",
            "Das Lied Where the devil dont go ist vom Saenger",
            "Das Lied dear Mama ist vom Saenger",
            "Das Lied Big Bang Theorie Theme ist vom Saenger",
            //105
            "Das Lied Tausend Tattoos ist vom Saenger",
            "Das Lied Pave Low ist vom Saenger",
            "Das Lied I Help You Hate Me ist vom Saenger",
            "Das Lied Holiday ist vom Saenger",
            "Das Lied Rockstar ist vom Saenger",
            //110
            "Das Lied Alles wird gut ist vom Saenger",
            "Das Lied Unendlich ist vom Saenger",
            "Das Lied Herz ist vom Saenger",
            "Das Lied verlierer ist vom Saenger",
            "Das Lied Meer ist vom Saenger",
            //115
            "Bist du dumm??",
            "JOKER",
            "JOKER",
            "Drache hat auf unserem Server mehr als 6k Nachrichten geschrieben und versendet",
            "Diesen Spruch gibt es im Harry Potter Universum -Accio",
            //120
            "Diesen Spruch gibt es im Harry Potter Universum -Avis",
            "Diesen Spruch gibt es im Harry Potter Universum -Deprimo",
            "Diesen Spruch gibt es im Harry Potter Universum -Engorgio",
            "Diesen Spruch gibt es im Harry Potter Universum -Imperio",
            "Diesen Spruch gibt es im Harry Potter Universum -Nox",
            //125
            "Diesen Spruch gibt es im Harry Potter Universum -Protego",
            "Diesen Spruch gibt es im Harry Potter Universum -Serpensortia",
            "Diesen Spruch gibt es im Harry Potter Universum -Specialis Revelio",
            "Diesen Spruch gibt es im Harry Potter Universum -Ratzeputz",
            "Diesen Spruch gibt es im Harry Potter Universum -Wingardium Leviosa",
            //130
            "Diesen Spruch gibt es im Harry Potter Universum -Aves",
            "Diesen Spruch gibt es im Harry Potter Universum -Ratzeputze",
            "Diesen Spruch gibt es im Harry Potter Universum -Morsmorder",
            "Diesen Spruch gibt es im Harry Potter Universum -Nux",
            "Diesen Spruch gibt es im Harry Potter Universum -Aqua gax",
            //135
            "Diesen Spruch gibt es im Harry Potter Universum -Protago",
            "Diesen Spruch gibt es im Harry Potter Universum -Wengarium Leviosa",
            "Diesen Spruch gibt es im Harry Potter Universum -Wangarium Leviosa",
            "Diesen Spruch gibt es im Harry Potter Universum -Wingardim Leviosa",
            "Diesen Spruch gibt es im Harry Potter Universum -Ofelom",
            //140
            "Den Film Der Schuh des Manitu guckten ueber 11 Millionen Menschen im Kino (in Deutschland)",
            "Den Film Das Dschungelbuch guckten ueber 27 Millionen Menschen im Kino (in Deutschland)",
            "Den Film Titanic guckten ueber 18 Millionen Menschen im Kino (in Deutschland)",
            "Den Film Die Brücke am Kwai guckten ueber 14 Millionen Menschen im Kino (in Deutschland)",
            "Den Film Ben Hur guckten ueber 13.5 Millionen Menschen im Kino (in Deutschland)",
            //145
            "Den Film Avatar – Aufbruch nach Pandora guckten ueber 20 Millionen Menschen im Kino (in Deutschland)",
            "Den Film Der Herr der Ringe: Die zwei Türme guckten ueber 22 Millionen Menschen im Kino (in Deutschland)",
            "Den Film 	James Bond 007 – Goldfinger guckten ueber 15 Millionen Menschen im Kino (in Deutschland)",
            "Den Film Harry Potter und die Kammer des Schreckens guckten ueber 11 Millionen Menschen im Kino (in Deutschland)",
            "Den Film Findet Nemo guckten ueber 10 Millionen Menschen im Kino (in Deutschland)",
            //150
            "Theodor Mommsen erhielt einen Nobelpreis",
            "Rudolf Eucken erhielt einen Nobelpreis",
            "Paul Heyse erhielt einen Nobelpreis",
            "Gerhart Hauptmann erhielt einen Nobelpreis",
            "Thomas Mann erhielt einen Nobelpreis",
            //155
            "Hermann Hesse erhielt einen Nobelpreis",
            "Nelly Sachs erhielt einen Nobelpreis",
            "Heinrich Boell erhielt einen Nobelpreis",
            "Guenter Grass erhielt einen Nobelpreis",
            "Herta Mueller erhielt einen Nobelpreis",
            //160
            "Emil Fischer erhielt einen Nobelpreis",
            "Adolf von Baeyer erhielt einen Nobelpreis",
            "Otto Wallach erhielt einen Nobelpreis",
            "Carl Bosch erhielt einen Nobelpreis",
            "Otto Hahn erhielt einen Nobelpreis",
            //165
            "Ernst Otto Fischer erhielt einen Nobelpreis",
            "Gerhard Ertl erhielt einen Nobelpreis",
            "Joachim Frank erhielt einen Nobelpreis",
            "Benjamin List erhielt einen Nobelpreis",
            "Harald zur Hausen erhielt einen Nobelpreis",
            //170
            "Wilhelm Conrad Röntgen erhielt einen Nobelpreis",
            "Ferdinand Braun erhielt einen Nobelpreis",
            "Wilhelm Wien erhielt einen Nobelpreis",
            "Max von Laue erhielt einen Nobelpreis",
            "Albert Einstein erhielt einen Nobelpreis",
            //175
            "Walther Bothe erhielt einen Nobelpreis",
            "J. Hans D. Jensen erhielt einen Nobelpreis",
            "Klaus von Klitzing erhielt einen Nobelpreis",
            "Robert Koch erhielt einen Nobelpreis",
            "Otto Warburg erhielt einen Nobelpreis",
            //180
            "Walther Bathe erhielt einen Nobelpreis",
            "Otto von Otto erhielt einen Nobelpreis",
            "Otto van der Lippe erhielt einen Nobelpreis",
            "Wilhelm Klaus Ertl erhielt einen Nobelpreis",
            "Ronald de Frunsk erhielt einen Nobelpreis",
            //185
            "Albert Zweistein erhielt einen Nobelpreis",
            "Tim Bux erhielt einen Nobelpreis",
            "Peter von der Spitz erhielt einen Nobelpreis",
            "Dieter Siemens erhielt einen Nobelpreis",
            "Tyszen Krupp erhielt einen Nobelpreis",
            //190
            "Yami Hunrae erhielt einen Nobelpreis",
            "Holger Bosch erhielt einen Nobelpreis",
            "Marie Cury erhielt einen Nobelpreis",
            "Paul Gerhard erhielt einen Nobelpreis",
            "Max Musterfrau erhielt einen Nobelpreis",
            //195
            "Lia Jouen erhielt einen Nobelpreis",
            "Dieter Wissing erhielt einen Nobelpreis",
            "Armin Laschet erhielt einen Nobelpreis",
            "Konrad Adenrauer erhielt einen Nobelpreis",
            "Mark Soeder erhielt einen Nobelpreis",
            //200
            "Irene Fischer erhielt einen Nobelpreis",
            "Tim Benzko erhielt einen Nobelpreis",
            "Helene Müllershauen erhielt einen Nobelpreis",
            "Udo Fischer erhielt einen Nobelpreis",
            "Otto van de Otto erhielt einen Nobelpreis",
            //205
            "Gertrud Rell erhielt einen Nobelpreis",
            "Lurg ot erhielt einen Nobelpreis",
            "Li Vern erhielt einen Nobelpreis",
            "Dom ej Hin erhielt einen Nobelpreis",
            "Numa list erhielt einen Nobelpreis",
            //210
            "Dieter Bohlen ist einer der 10 reichsten Menschen Deutschlands",
            "Bonn ist eine Hauptstadt",
            "Sydney ist eine Hauptstadt",
            "Nuernberg ist eine Hauptstadt",
            "Hamm ist eine Hauptstadt",
            //215
            "Kiel ist eine Hauptstadt",
            "Hannover ist eine Hauptstadt",
            "Magdeburg ist eine Hauptstadt",
            "Schwerin ist eine Hauptstadt",
            "Potsdam ist eine Hauptstadt",
            //220
            "Dresden ist eine Hauptstadt",
            "Erfurt ist eine Hauptstadt",
            "Duesseldorf ist eine Hauptstadt",
            "Wiesbaden ist eine Hauptstadt",
            "Mainz ist eine Hauptstadt",
            //225
            "Wiessbaden ist eine Hauptstadt",
            "Dueseldorf ist eine Hauptstadt",
            "Meinz ist eine Hauptstadt",
            "Sarbruecken ist eine Hauptstadt",
            "Frankfurt ist eine Hauptstadt",
            //230
            "Koeln ist eine Hauptstadt",
            "Aachen ist eine Hauptstadt",
            "Erfort ist eine Hauptstadt",
            "Kihl ist eine Hauptstadt",
            "Hannoffer ist eine Hauptstadt",
            //235
            "Loki ist eine Marvel Serie",
            "Daredevil ist eine Marvel Serie",
            "WandaVision ist eine Marvel Serie",
            "Ms. Marvel ist eine Marvel Serie",
            "What if ist eine Marvel Serie",
            //240
            "Captain Marval ist eine Marvel Serie",
            "Iron Man ist eine Marvel Serie",
            "Thor ist eine Marvel Serie",
            "Stan Lee ist eine Marvel Serie",
            "Muun Knight ist eine Marvel Serie",
            //245
            "Aletheia ist ein Gott in der griechischen Mythologie",
            "Asklepios ist ein Gott in der griechischen Mythologie",
            "Hekate ist ein Gott in der griechischen Mythologie",
            "Horen ist ein Gott in der griechischen Mythologie",
            "Hades ist ein Gott in der griechischen Mythologie",
            //250
            "Ares ist ein Gott in der griechischen Mythologie",
            "Poseidon ist ein Gott in der griechischen Mythologie",
            "Zeus ist ein Gott in der griechischen Mythologie",
            "Iris ist ein Gott in der griechischen Mythologie",
            "Pan ist ein Gott in der griechischen Mythologie",
            //255
            "Plutos ist ein Gott in der griechischen Mythologie",
            "Zelos ist ein Gott in der griechischen Mythologie",
            "Hera ist ein Gott in der griechischen Mythologie",
            "Hephaistos ist ein Gott in der griechischen Mythologie",
            "Athene ist ein Gott in der griechischen Mythologie",
            //260
            "Jupiter ist ein Gott in der griechischen Mythologie",
            "Mars ist ein Gott in der griechischen Mythologie",
            "Pann ist ein Gott in der griechischen Mythologie",
            "Herckules ist ein Gott in der griechischen Mythologie",
            "Daniel ist ein Gott in der griechischen Mythologie",
            //265
            "Neptun ist ein Gott in der griechischen Mythologie",
            "Uranos ist ein Gott in der griechischen Mythologie",
            "Saturn ist ein Gott in der griechischen Mythologie",
            "Hamistos ist ein Gott in der griechischen Mythologie",
            "Nomus ist ein Gott in der griechischen Mythologie",
            //270
            "Libesos ist ein Gott in der griechischen Mythologie",
            "Nym ist ein Gott in der griechischen Mythologie",
            "Po ist ein Gott in der griechischen Mythologie",
            "Sella ist ein Gott in der griechischen Mythologie",
            "Fenus ist ein Gott in der griechischen Mythologie",
            //275
            "Mars ist ein Gott in der roemischen Mythologie",
            "Jupiter ist ein Gott in der roemischen Mythologie",
            "Neptun ist ein Gott in der roemischen Mythologie",
            "Ceres ist ein Gott in der roemischen Mythologie",
            "Vulcanus ist ein Gott in der roemischen Mythologie",
            //280
            "Ares ist ein Gott in der roemischen Mythologie",
            "Hades ist ein Gott in der roemischen Mythologie",
            "Artemis ist ein Gott in der roemischen Mythologie",
            "Apollon ist ein Gott in der roemischen Mythologie",
            "Hermes ist ein Gott in der roemischen Mythologie",
            //285
            "Juno ist der roemische Gott fuer den griechischen Gott Hera",
            "Neptun ist der roemische Gott fuer den griechischen Gott Podeidon",
            "Minerva ist der roemische Gott fuer den griechischen Gott Athene",
            "Diana ist der roemische Gott fuer den griechischen Gott Artemis",
            "Vesta ist der roemische Gott fuer den griechischen Gott Hestia",
            //290
            "Vesta ist der roemische Gott fuer den griechischen Gott Athene",
            "Diana ist der roemische Gott fuer den griechischen Gott Hestia",
            "Minerva ist der roemische Gott fuer den griechischen Gott Artemis",
            "Mars ist der roemische Gott fuer den griechischen Gott Zeus",
            "Merkur ist der roemische Gott fuer den griechischen Gott Ares",
            //295
            "Aa ist ein Gott in der aegyptischen Mythologie",
            "Aha ist ein Gott in der aegyptischen Mythologie",
            "Abi ist ein Gott in der aegyptischen Mythologie",
            "Amaa ist ein Gott in der aegyptischen Mythologie",
            "Asch ist ein Gott in der aegyptischen Mythologie",
            //300
            "Aaa ist ein Gott in der aegyptischen Mythologie",
            "Ash ist ein Gott in der aegyptischen Mythologie",
            "Aib ist ein Gott in der aegyptischen Mythologie",
            "Aama ist ein Gott in der aegyptischen Mythologie",
            "Ah ist ein Gott in der aegyptischen Mythologie",
            //305
            "Balder ist ein Gott in der nordischen Mythologie",
            "Ymir ist ein Gott in der nordischen Mythologie",
            "Mimir ist ein Gott in der nordischen Mythologie",
            "Njoerd ist ein Gott in der nordischen Mythologie",
            "Surt ist ein Gott in der nordischen Mythologie",
            //310
            "Barder ist ein Gott in der nordischen Mythologie",
            "Siegus ist ein Gott in der nordischen Mythologie",
            "Freyaa ist ein Gott in der nordischen Mythologie",
            "Oddin ist ein Gott in der nordischen Mythologie",
            "Tohr ist ein Gott in der nordischen Mythologie",
            //315
            "In der nordischen Mythologie unterscheidet man unter diesen 3. Goetter Arten Joetunn, Wanen, Asen",
            "In der nordischen Mythologie unterscheidet man unter diesen 3. Goetter Arten Temen, Wanen, Asen",
            "Der Weltenbaum in der nordischen Mythologie wird Yggdrasil genannt",
            "Der Weltenbaum in der nordischen Mythologie wird Ygdrasil genannt",
            "Riesen stehen in der nordischen Mythologie fuer staerke und das gute",
            //320
            "Die Neckar (Fluss) fliesst durch Deutschland",
            "Die Isar (Fluss) fliesst durch Deutschland",
            "Die Aller (Fluss) fliesst durch Deutschland",
            "Die Weiße Elster (Fluss) fliesst durch Deutschland",
            "Die Warnow (Fluss) fliesst durch Deutschland",
            //325
            "Die Katoffelsalat (Fluss) fliesst durch Deutschland",
            "Der Warwic (Fluss) fliesst durch Deutschland",
            "Die Reene (Fluss) fliesst durch Deutschland",
            "Die hohe Tanne (Fluss) fliesst durch Deutschland",
            "Die Sea of thiefes (Fluss) fliesst durch Deutschland",
            //330
            "Skateboarding wurde zunaechst als \"Sidewalk Surfing\" bezeichnet",
            "Der Olli (Skateboard Trick) wurde von Olli Freak (youtuber) erfunden",
            "Der erste Skate-Park wurde im Jahr 1965 gebaut",
            "Im Jahr 1998 landete Tony Hawk den 900",
            "Rodney Mullen erfand die meisten Flip- und Spin-Tricks",
            //335
            "Die groesste Treppe, die jemals mit einem Ollie ueberwunden wurde, bestand aus 25 Einzelstufen",
            "Die groesste Treppe, die jemals mit einem Ollie ueberwunden wurde, bestand aus 20 Einzelstufen",
            "Skateboarding wurde 2020 bei den Olympischen Spielen aufgenommen",
            "Skateboarding wurde 2016 bei den Olympischen Spielen aufgenommen",
            "In Amerika befinden sich weniger als 3000 Skate-Parks",
            //340
            "Dungeons & Dragons gilt als erstes Pen-&-Paper-Rollenspiel",
            "Dungeons & Dragons wurde von Gary Gygax und Dave Arneson erfunden",
            "Dungeons & Dragons wurde erstmals 1974 erfolgreich vertrieben (in Amerika)",
            "Nach dem alter 18 kommt das alter 19",
            "Ein Fussball prallt oft am Umut Bulut ab, da er Fussballer Spieler ist",
            //345
            "Dungeons & Dragons wurde von Gary Gyg und Dave Areson erfunden",
            "Ein Fussball prallt oft am Umut Bulut ab, da er Handballer Spieler ist",
            "Nach dem alter 18 kommt das alter 21",
            "Dungeons & Dragons wurde erstmals 1964 erfolgreich vertrieben (in Amerika)",
            "Dungeons & Dragons gilt als erstes Handy-&-Paper-Rollenspiel",
            //350
            "Wie viele amtliche Zeitzonen hat Russland",
            "Was ist die nationale Blume Japans",
            "Wie viele Streifen sind auf der US-Flagge",
            "Was ist das Nationaltier Australiens",
            "Wie nennst man ein maennliches Schwein",
            //355
            "Wie viele Oscars gewann der Film Titanic",
            "Wann wurde Queen Elisabeth II. zur Koenigin gekroent",
            "Aus wie vielen Einzelknochen besteht eine menschliche Hand",
            "Wer war 1991 Weltfussballer des Jahres?",
            "Wer war 1992 Weltfussballer des Jahres?",
            //360
            "Wer war 1993 Weltfussballer des Jahres?",
            "Wer war 1994 Weltfussballer des Jahres?",
            "Wer war 1995 Weltfussballer des Jahres?",
            "Wer war 1996 Weltfussballer des Jahres?",
            "Wer war 1997 Weltfussballer des Jahres?",
            //365
            "Wer war 1998 Weltfussballer des Jahres?",
            "Wer war 1999 Weltfussballer des Jahres?",
            "Wer war 2000 Weltfussballer des Jahres?",
            "Wer war 2001 Weltfussballer des Jahres?",
            "Wer war 2002 Weltfussballer des Jahres?",
            //370
            "Wer war 2003 Weltfussballer des Jahres?",
            "Wer war 2004 Weltfussballer des Jahres?",
            "Wer war 2005 Weltfussballer des Jahres?",
            "Wer war 2006 Weltfussballer des Jahres?",
            "Wer war 2007 Weltfussballer des Jahres?",
            //375
            "Wer war 2008 Weltfussballer des Jahres?",
            "Wer war 2009 Weltfussballer des Jahres?",
            "Wer war 2010 Weltfussballer des Jahres?",
            "Wer war 2011 Weltfussballer des Jahres?",
            "Wer war 2012 Weltfussballer des Jahres?",
            //380
            "Wer war 2013 Weltfussballer des Jahres?",
            "Wer war 2014 Weltfussballer des Jahres?",
            "Wer war 2015 Weltfussballer des Jahres?",
            "Wer war 2016 Weltfussballer des Jahres?",
            "Wer war 2017 Weltfussballer des Jahres?",
            //385
            "Wer war 2018 Weltfussballer des Jahres?",
            "Wer war 2019 Weltfussballer des Jahres?",
            "Wer war 2020 Weltfussballer des Jahres?",
            "Wer war 2021 Weltfussballer des Jahres?",
            "Wer war 2022 Weltfussballer des Jahres?",
            //390
    };

    String[] faktenAntwortMoeglichkeiten = new String[]	{
            "Ja, na klar | WTF! NEIN! | Er heisst im echten Leben auch Drache",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //5
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //10
            "Albert Einstein | Henry Ford | Nikola Tesla | Konfuzis | Aristoteles",
            "Henry Ford | Ludwig Welm | Bastian Miele | Konrad Benz | Philip Siemens",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //15
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //20
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //25
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //30
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //35
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //40
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //45
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //50
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //55
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //60
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //65
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //70
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //75
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //80
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //85
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //90
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //95
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //100
            "Post Malone | Royal Deluxe | 2 pac | Boss Hoss | Dieter Bohlen",
            "2 pac | Peter Fox | Genetikk | Dame | Julien Bam",
            "Elle King | 2 pac | Nina Simone | 5 seconds of summer | Lizzo",
            "2 pac | Maroon 5 | Dj Kel | Dy BOB | David Guetta",
            "2 pac | The Score | The Script | Barenaked Ladies | Gentelman",
            //105
            "Sido | Dame | Sunrise Avenue | Green Day | Nickelback",
            "Sido | Dame | Sunrise Avenue | Green Day | Nickelback",
            "Sido | Dame | Sunrise Avenue | Green Day | Nickelback",
            "Sido | Dame | Sunrise Avenue | Green Day | Nickelback",
            "Sido | Dame | Sunrise Avenue | Green Day | Nickelback",
            //110
            "Bushido | Bozza | Sido | LUNA | Luciano",
            "Bushido | Bozza | Sido | LUNA | Luciano",
            "Bushido | Bozza | Sido | LUNA | Luciano",
            "Bushido | Bozza | Sido | LUNA | Luciano",
            "Bushido | Bozza | Sido | LUNA | Luciano",
            //115
            "JA! | Nein du Wixxer | Wenn ich dafuer Draches Adresse bekomme :) | Bist du es | Warum fragst du",
            "Schreib JOKER",
            "Schreib JOKER",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //120
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //125
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //130
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //135
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //140
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //145
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //150
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //155
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //160
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //165
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //170
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //175
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //180
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //185
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //190
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //195
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //200
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //205
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //210
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //215
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //220
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //225
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //230
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //235
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //240
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //245
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //250
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //255
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //260
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //265
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //270
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //275
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //280
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //285
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //290
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //295
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //300
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //305
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //310
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //315
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //320
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //325
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            "ja | nein",
            //330
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //335
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //340
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //345
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            "Stimmt | Stimmt nicht",
            //350
            "4 | 6 | 9 | 11 | 14",
            "Rose | Chrysantheme | Kirschbluete | sakura | Paeonie",
            "16 | 9 | 11 | 13 | 14",
            "Kroete | Emu | Kaenguru | Koala | Wombat",
            "Eber | Boerge | Kater | Sauer | Erpel",
            //355
            "16 | 9 | 11 | 13 | 14",
            "1947 | 1957 | 1949 | gar nicht | 1953",
            "16 | 27 | 19 | 35 | 57",
            "Christiano Ronaldo | Lionel Messi | Lothar Matthaeus | Marco van Basten | George Weah",
            "Christiano Ronaldo | Lionel Messi | Lothar Matthaeus | Marco van Basten | George Weah",
            //360
            "Christiano Ronaldo | Lionel Messi | Roberto Baggio | Marco van Basten | George Weah",
            "Christiano Ronaldo | Lionel Messi | Lothar Matthaeus | Marco van Basten | Romario",
            "Christiano Ronaldo | Lionel Messi | Lothar Matthaeus | Ronaldo | George Weah",
            "Ronaldo | Lionel Messi | Lothar Matthaeus | Marco van Basten | George Weah",
            "Christiano Ronaldo | Lionel Messi | Ronaldo | Zinedine Zidane | George Weah",
            //365
            "Rivaldo | Lionel Messi | Roberto Baggio | Oliver Kahn | Zinedine Zidane",
            "Rivaldo | Lionel Messi | Roberto Baggio | Oliver Kahn | Zinedine Zidane",
            "Christiano Ronaldo | Lionel Messi | Zinedine Zidane | Luis Figo | Romario",
            "Christiano Ronaldo | Lionel Messi | Luis Figo | Ronaldo | George Weah",
            "Ronaldo | Lionel Messi | Lothar Matthaeus | Marco van Basten | Ronaldo",
            //370
            "Christiano Ronaldo | Lionel Messi | Ronaldo | Zinedine Zidane | George Weah",
            "Rivaldo | Lionel Messi | Ronaldinho | Oliver Kahn | Fabio Cannavaro",
            "Christiano Ronaldo | Lionel Messi | Zinedine Zidane | Ronaldinho | Romario",
            "Christiano Ronaldo | Lionel Messi | Ronaldinho | Ronaldo | Fabio Cannavaro",
            "Ronaldo | Lionel Messi | Kaka | Marco van Basten | Ronaldo",
            //375
            "Christiano Ronaldo | Kaka | Ronaldo | Zinedine Zidane | George Weah",
            "Rivaldo | Lionel Messi | Ronaldinho | Oliver Kahn | Fabio Cannavaro",
            "Christiano Ronaldo | Lionel Messi | Zinedine Zidane | Ronaldinho | Romario",
            "Christiano Ronaldo | Lionel Messi | Ronaldinho | Ronaldo | Fabio Cannavaro",
            "Ronaldo | Lionel Messi | Kaka | Marco van Basten | Ronaldo",
            //380
            "Christiano Ronaldo | Kaka | Ronaldo | Zinedine Zidane | George Weah",
            "Christiano Ronaldo | Lionel Messi | Ronaldinho | Oliver Kahn | Fabio Cannavaro",
            "Christiano Ronaldo | Lionel Messi | Zinedine Zidane | Ronaldinho | Romario",
            "Christiano Ronaldo | Lionel Messi | Ronaldinho | Ronaldo | Fabio Cannavaro",
            "Christiano Ronaldo | Lionel Messi | Kaka | Marco van Basten | Ronaldo",
            //385
            "Christiano Ronaldo | Kaka | Ronaldo | Zinedine Zidane | Luka Modric",
            "Christiano Ronaldo | Lionel Messi | Ronaldinho | Oliver Kahn | Fabio Cannavaro",
            "Christiano Ronaldo | Lionel Messi | Zinedine Zidane | Ronaldinho | Robert Lewandowski",
            "Christiano Ronaldo | Lionel Messi | Ronaldinho | Robert Lewandowski | Fabio Cannavaro",
            "Christiano Ronaldo | Lionel Messi | Kaka | Marco van Basten | Ronaldo",
            //390


    };

    String[] faktenAntworten = new String[]	{
            "WIr werden es nIe wIssen (9746592837497587976624364285819)",
            "Stimmt",
            "Stimmt",
            "Stimmt nicht",
            "Stimmt",
            //5
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //10
            "Nikola Tesla",
            "Henry Ford",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //15
            "Stimmt nicht",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //20
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //25
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //30
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //35
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //40
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //45
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //50
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //55
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //60
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //65
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //70
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //75
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //80
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //85
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt",
            //90
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //95
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //100
            "Royal Deluxe",
            "Genetikk",
            "Elle King",
            "2 pac",
            "Barenaked Ladies",
            //105
            "Sido",
            "Dame",
            "Sunrise Avenue",
            "Green Day",
            "Nickelback",
            //110
            "Bushido",
            "Bozza",
            "Sido",
            "LUNA",
            "Luciano",
            //115
            "Das war offensichtlich eine Scherz-Frage (1563463726512645831976346126835482364728516147518)",
            "JOKER",
            "Du wurdest geintet",
            "Stimmt",
            "Stimmt",
            //120
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //125
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //130
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //135
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //140
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //145
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //150
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //155
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //160
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //165
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //170
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //175
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //180
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //185
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //190
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //195
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //200
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //205
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //210
            "nein",
            "nein",
            "nein",
            "nein",
            "nein",
            //215
            "ja",
            "ja",
            "ja",
            "ja",
            "ja",
            //220
            "ja",
            "ja",
            "ja",
            "ja",
            "ja",
            //225
            "nein",
            "nein",
            "nein",
            "nein",
            "nein",
            //230
            "nein",
            "nein",
            "nein",
            "nein",
            "nein",
            //235
            "ja",
            "ja",
            "ja",
            "ja",
            "ja",
            //240
            "nein",
            "nein",
            "nein",
            "nein",
            "nein",
            //245
            "ja",
            "ja",
            "ja",
            "ja",
            "ja",
            //250
            "ja",
            "ja",
            "ja",
            "ja",
            "ja",
            //255
            "ja",
            "ja",
            "ja",
            "ja",
            "ja",
            //260
            "nein",
            "nein",
            "nein",
            "nein",
            "nein",
            //265
            "nein",
            "nein",
            "nein",
            "nein",
            "nein",
            //270
            "nein",
            "nein",
            "nein",
            "nein",
            "nein",
            //275
            "ja",
            "ja",
            "ja",
            "ja",
            "ja",
            //280
            "nein",
            "nein",
            "nein",
            "nein",
            "nein",
            //285
            "ja",
            "ja",
            "ja",
            "ja",
            "ja",
            //290
            "nein",
            "nein",
            "nein",
            "nein",
            "nein",
            //295
            "ja",
            "ja",
            "ja",
            "ja",
            "ja",
            //300
            "nein",
            "nein",
            "nein",
            "nein",
            "nein",
            //305
            "ja",
            "ja",
            "ja",
            "ja",
            "ja",
            //310
            "nein",
            "nein",
            "nein",
            "nein",
            "nein",
            //315
            "Stimmt",
            "Stimmt nicht",
            "Stimmt",
            "Stimmt nicht",
            "Stimmt nicht",
            //320
            "ja",
            "ja",
            "ja",
            "ja",
            "ja",
            //325
            "nein",
            "nein",
            "nein",
            "nein",
            "nein",
            //330
            "Stimmt",
            "Stimmt nicht",
            "Stimmt",
            "Stimmt nicht",
            "Stimmt",
            //335
            "Stimmt",
            "Stimmt nicht",
            "Stimmt",
            "Stimmt nicht",
            "Stimmt nicht",
            //340
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            "Stimmt",
            //345
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            "Stimmt nicht",
            //350
            "11",
            "Chrysantheme",
            "13",
            "Kaenguru",
            "Eber",
            //355
            "11",
            "1953",
            "27",
            "Lothar Matthaeus",
            "Marco van Basten",
            //360
            "Roberto Baggio",
            "Romario",
            "George Weah",
            "Ronaldo",
            "Ronaldo",
            //365
            "Zinedine Zidane",
            "Rivaldo",
            "Zinedine Zidane",
            "Luis Figo",
            "Ronaldo",
            //370
            "Zinedine Zidane",
            "Ronaldinho",
            "Ronaldinho",
            "Fabio Cannavaro",
            "Kaka",
            //375
            "Cristiano Ronaldo",
            "Lionel Messi",
            "Lionel Messi",
            "Lionel Messi",
            "Lionel Messi",
            //380
            "Cristiano Ronaldo",
            "Cristiano Ronaldo",
            "Lionel Messi",
            "Cristiano Ronaldo",
            "Cristiano Ronaldo",
            //385
            "Luka Modric",
            "Lionel Messi",
            "Robert Lewandowski",
            "Robert Lewandowski",
            "Lionel Messi",
            //390
    };
}
